### ISSUE TITLE
[Question]: How to make the dark mode still when reflash the page

### ISSUE THREAD

**Issue by 7ity** [craftzdog/craftzdog-homepage#12]
Hello. Nice to meet u!

It's my first time to reach that more advanced web toghlogy -D.
How to make the dark mode still when reflash the page.

Kind regards,
Willie Xu -- A high school student
 China

**Comment by K3NZ11** [comment]
By default, the theme should be `dark`. However, it could be overridden by your current operating system theme. To avoid your os theme overriding the default dark mode, you can change `useSystemColorMode` to `false` in this **[file](https://github.com/craftzdog/craftzdog-homepage/blob/master/lib/theme.js).**

**Comment by 7ity** [comment]
> By default, the theme should be `dark`. However, it could be overridden by your current operating system theme. To avoid your os theme overriding the default dark mode, you can change `useSystemColorMode` to `false` in this **[file](https://github.com/craftzdog/craftzdog-homepage/blob/master/lib/theme.js).**

The default is light theme whatever it applies dark on the OS. The issue is that the dark theme will be inactived when reflash it. By the way I don't want get rid of following the system theme. How can I resolve it?

**Comment by K3NZ11** [comment]
You'll need to save your theme somewhere persistent like your browser cookie. Otherwise, after refreshing the page it will always reset back to your initial theme.

**Comment by K3NZ11** [comment]
By default, `@chakra-ui` already store the current theme status on your browser local storage. However, since we override their configuration, after refreshing the page it will always start with the value in our configuration. To solve this, you could remove the `config` variable in `lib/theme.js` file and the theme should stay the same even after you refresh the page.

```javascript
const theme = extendTheme({ styles, components, fonts, colors })
export default theme
```

**Comment by K3NZ11** [comment]
So, the problem was because `@chakra-ui` is unable to read the value from localStorage or cookie properly because we're using server-side rendering. To fix this, you need to provide the cookie object when each page is rendered.

```javascript
// components/chakra.js (new file)

import { ChakraProvider, cookieStorageManager, localStorageManager } from '@chakra-ui/react'
import theme from '../lib/theme'

export default function Chakra({ cookies, children }) {
  const colorModeManager =
    typeof cookies === 'string'
      ? cookieStorageManager(cookies)
      : localStorageManager

  return (
    <ChakraProvider theme={theme} colorModeManager={colorModeManager}>
      {children}
    </ChakraProvider>
  )
}

export function getServerSideProps({ req }) {
  return {
    props: {
      cookies: req.headers.cookie ?? ''
    }
  }
}
```

```javascript
// pages/_app.js

import Layout from '../components/layouts/main'
import Fonts from '../components/fonts'
import { AnimatePresence } from 'framer-motion'
import Chakra from '../components/chakra'

function Website({ Component, pageProps, router }) {
  return (
    <Chakra cookies={pageProps.cookies}>
      <Fonts />
      <Layout router={router}>
        <AnimatePresence exitBeforeEnter initial={true}>
          <Component {...pageProps} key={router.route} />
        </AnimatePresence>
      </Layout>
    </Chakra>
  )
}

export default Website
```

```javascript
// add this at the bottom line of all pages (e.g. pages/index.js)
export { getServerSideProps } from '../components/chakra'
```

**Comment by itforweb666** [comment]
It successful work! Thank you.
Do this support over time?

For instance in JavaScript:

```JavaScript
if (
  new Date().getHours() >= 19 ||
  new Date().getHours() < 7 )
   {
   document.body.classList.toggle("dark")}
```

**Comment by K3NZ11** [comment]
@itforweb666 I don't think changing the class of the html element would do the job in this case. However, I think you could manually update the value in your browser cookie. Therefore, when the page initially load, it will read the value from there.
