### ISSUE TITLE
[ Issue ] Dark Mode Again

### ISSUE THREAD

**Issue by xuwillie** [craftzdog/craftzdog-homepage#16]
Hi, I found that 404 page cannot still theme mode!

**Comment by Harry-Hopkinson** [comment]
I will have a look at it

**Comment by craftzdog** [comment]
cc: @K3NZ11

**Comment by Harry-Hopkinson** [comment]
404 pages can not have cookies saved on them for themes

**Comment by Harry-Hopkinson** [comment]
I am just working on 404 support

**Comment by Harry-Hopkinson** [comment]
https://github.com/craftzdog/craftzdog-homepage/pull/17
