### ISSUE TITLE
Warning in the console in dev environement

### ISSUE THREAD

**Issue by Rebraxin** [craftzdog/craftzdog-homepage#2]
I found a way to this little

![image](https://user-images.githubusercontent.com/52607153/138017183-c69562b6-141f-495a-8fc7-fdbcda48bd51.png)

Its by adding this into the `<menu>` in `~/src/components/navbar.js`

![image](https://user-images.githubusercontent.com/52607153/138018049-dcfe87fa-596e-4acc-bd7f-a2482a83863b.png)

Hope it help, i do like to keep a clean console :)

Thx for sharing Takuya!

**Comment by craftzdog** [comment]
Thanks for the suggestion! Yeah, it works.
Note that the SSR for the dropdown menu is no longer working as it's now lazy.
