### ISSUE TITLE
Why is this person using the Takuya Matsuyama code?

### ISSUE THREAD

**Issue by Prince-Gizard** [craftzdog/craftzdog-homepage#20]
https://harryhopkinson.vercel.app/
MIT License.

You can create your own homepage for free without notifying me by forking this project under the following conditions:

Add a link to my homepage
Do not use the 3d voxel dog

**Comment by Harry-Hopkinson** [comment]
Why your homepage?

**Comment by Harry-Hopkinson** [comment]
There is no LICENSE - it is a tutorial

**Comment by Harry-Hopkinson** [comment]
And I am a contributor - you are not

**Comment by craftzdog** [comment]
Check out the license section in README: https://github.com/craftzdog/craftzdog-homepage#license

**Comment by Harry-Hopkinson** [comment]
Ok sorry

**Comment by craftzdog** [comment]
No problem :)

**Comment by Prince-Gizard** [comment]
Плохие мальчишки будут наказаны! 
Пёс-призрак всегда начеку 🐶👻
