### ISSUE TITLE
After navigation page jumps to top before navigating 

### ISSUE THREAD

**Issue by 22chrs** [craftzdog/craftzdog-homepage#25]
Great Job! Really like your minimalistic design. I try to reuse your website and found a bug, which also exists on your page:

1. For example navigate to https://www.craftz.dog/works
2. Scroll down to the bottom of the page
3. Click on for example "Pichu*Pichu"
4. BUG: Now the works page jumps to the top (of the works page) before the actual navigating to (https://www.craftz.dog/works/pichu2) begins
-> In my eyes it is annoying to see a fraction of a second the to of the works page before the navigation.

Do you know how to fix this? I tried it myself but I do not get along.
Thanks

PS
I am using a 15" MacBook Pro. Maybe my screen is smaller than most desktop systems and you didn't see the bug?

**Comment by craftzdog** [comment]
Check out this issue for more detail: https://github.com/framer/motion/issues/626

**Comment by 22chrs** [comment]
Works like a charm! ❤️

**Comment by 22chrs** [comment]
You missed the the three MenuList links in the nabber file. 
Personally I would suggest to smooth blend in de 3D dog threeJS file after navigation to a new page.
