### ISSUE TITLE
How was the 3d voxel dog created by you

### ISSUE THREAD

**Issue by CoXier** [craftzdog/craftzdog-homepage#30]
Thanks for your awesome job ,especially the the 3d voxel dog, amazing ！

I have a question about the 3d voxel dog. How was it created?

**Comment by Harry-Hopkinson** [comment]
There is a video upon the subject

**Comment by CoXier** [comment]
> There is a video upon the subject

Where is it ? I cannot find it.

However my question is about how to create this 3d model? By which tool?

**Comment by Harry-Hopkinson** [comment]
https://www.youtube.com/watch?v=vHHihuW0_4M
