### ISSUE TITLE
How to change the moving icon

### ISSUE THREAD

**Issue by NotLuca** [craftzdog/craftzdog-homepage#31]
The cat with PC one

**Comment by Harry-Hopkinson** [comment]
Just change the image path to another voxel image.

**Comment by NotLuca** [comment]
okay

**Comment by Harry-Hopkinson** [comment]
I can show you where if you need to.

**Comment by NotLuca** [comment]
> I can show you where if you need to.

Ok

**Comment by Harry-Hopkinson** [comment]
Change the path code on voxel-dog.js to the path of your new moving model.

```javascript
loadGLTFModel(scene, '/dog.glb', {
        receiveShadow: false,
        castShadow: false
      }).then(() => {
        animate()
        setLoading(false)
      })
``` 

Change dog.glb to the path of your model.

**Comment by NotLuca** [comment]
> Change the path code on voxel-dog.js to the path of your new moving model.
> 
> ```js
> loadGLTFModel(scene, '/dog.glb', {
>         receiveShadow: false,
>         castShadow: false
>       }).then(() => {
>         animate()
>         setLoading(false)
>       })
> ```
> 
> Change dog.glb to the path of your model.

thx

**Comment by Harry-Hopkinson** [comment]
No problem.
