### ISSUE TITLE
2 3D model at top and bottom in the page

### ISSUE THREAD

**Issue by capedcrusader743** [craftzdog/craftzdog-homepage#36]
Hi,

I'm following the tutorial in adding a 3D model using Three. I've been watching that part of the tutorial again and compare my code with the github version to see if there is any typo, but I didn't see any. Can you show me where I could be doing wrong? Thank you.

**Comment by Harry-Hopkinson** [comment]
Can you share the code for the 3D Model?

**Comment by capedcrusader743** [comment]
This is my model.js
`import { GLTFLoader } from 'three/examples/jsm/loaders/GLTFLoader'

export function loadGLTFModel(
    scene,
    glbPath,
    options = { receiveShadow: true, castShadow: true }
) {
    const { receiveShadow, castShadow } = options
    return new Promise((resolve, reject) => {
        const loader = new GLTFLoader()

        loader.load(
            glbPath,
            gltf => {
                const obj = gltf.scene
                obj.name = 'ame'
                obj.position.y = 0
                obj.position.x = 0
                obj.receiveShadow = receiveShadow
                obj.castShadow = castShadow
                scene.add(obj)

                obj.traverse(function (child) {
                    if(child.isMesh) {
                        child.castShadow = castShadow
                        child.receiveShadow = receiveShadow
                    }
                })

                resolve(obj)
            },
            undefined,
            function (error) {
                reject(error)
            }
        )
    })
}`

voxel-model.js
`
import { useState, useEffect, useRef, useCallback } from 'react'
import * as THREE from 'three'
import { OrbitControls } from 'three/examples/jsm/controls/OrbitControls'
import { loadGLTFModel } from '../libs/model';
import { AmeSpinner, AmeContainer } from './voxel-ame-loader'
import { Box, Spinner } from '@chakra-ui/react'

function easeOutCirc(x) {
    return Math.sqrt(1 - Math.pow(x - 1, 4))
}

const VoxelAme = () => {
    const refContainer = useRef()
    const [loading, setLoading] = useState(true)
    const [renderer, setRenderer] = useState()
    const [_camera, setCamera] = useState()
    const [target] = useState(new THREE.Vector3(-0.5, 1.2, 0))
    const [initialCameraPosition] = useState(
        new THREE.Vector3(
            20 * Math.sin(0.2 * Math.PI),
            10,
            20 * Math.cos(0.2 * Math.PI)
        )
    )
    const [scene] = useState(new THREE.Scene())
    const [_controls, setControls] = useState()

    const handleWindowResize = useCallback(() => {
        const { current: container } = refContainer
        if (container && renderer) {
            const scW = container.clientWidth
            const scH = container.clientHeight

            renderer.setSize(scW, scH)
        }
    }, [renderer])

    /* eslint-disable react-hooks/exhaustive-deps */
    useEffect(() => {
        const { current: container } = refContainer
        if (container && !renderer) {
            const scW = container.clientWidth
            const scH = container.clientHeight

            const renderer = new THREE.WebGLRenderer({
                antialias: true,
                alpha: true
            })
            renderer.setPixelRatio(window.devicePixelRatio)
            renderer.setSize(scW, scH)
            renderer.outputEncoding = THREE.sRGBEncoding
            container.appendChild(renderer.domElement)
            setRenderer(renderer)

            // 640 -> 240
            // 8 -> 6
            const scale = scH * 0.005 + 4.8
            const camera = new THREE.OrthographicCamera(
                -scale,
                scale,
                scale,
                -scale,
                0.01,
                50000
            )
            camera.position.copy(initialCameraPosition)
            camera.lookAt(target)
            setCamera(camera)

            const ambientLight = new THREE.AmbientLight(0xcccccc, 1)
            scene.add(ambientLight)

            const controls = new OrbitControls(camera, renderer.domElement)
            controls.autoRotate = true
            controls.target = target
            setControls(controls)

            loadGLTFModel(scene, '/dog.glb', {
                receiveShadow: false,
                castShadow: false
            }).then(() => {
                animate()
                setLoading(false);
            })

            let req = null
            let frame = 0
            const animate = () => {
                req = requestAnimationFrame(animate)

                frame = frame <= 100 ? frame + 1 : frame
                console.log(frame)

                if(frame <= 100) {
                    const p = initialCameraPosition
                    const rotSpeed = -easeOutCirc(frame / 120) * Math.PI * 20
                    
                    camera.position.y = 10
                    camera.position.x = p.x * Math.cos(rotSpeed) + p.z * Math.sin(rotSpeed)
                    camera.position.z = p.z * Math.cos(rotSpeed) - p.x * Math.sin(rotSpeed)
                    camera.lookAt(target)
                } else {
                    controls.update()
                }

                renderer.render(scene, camera)
            } 

            return () => {
                console.log('unmount')
                cancelAnimationFrame(req)
                renderer.dispose()
            }
        }
    }, [])

    useEffect(() => {
        window.addEventListener('resize', handleWindowResize, false)
        return() => {
            window.removeEventListener('resize', handleWindowResize, false)
        }
    }, [renderer, handleWindowResize])

    return (
        <AmeContainer ref={refContainer}>
            {loading && <AmeSpinner />}
        </AmeContainer>
        // <Box
        //     ref={refContainer}
        //     className="voxel-ame"
        //     m="auto"
        //     at={['-20px', '-60px', '-120px']}
        //     mb={['-40px', '-140px', '-200px']}
        //     w={[280, 480, 640]}
        //     h={[280, 480, 640]}
        //     position='relative'
        // >
        //     {loading && (
        //             <Spinner
        //             size='xl'
        //             position='absolute'
        //             left='50%'
        //             top='50%'
        //             ml='calc(0px - var(--spinner-size) / 2)'
        //             mt='calc(0px - var(--spinner-size))'
        //         />
        //     )}
        //     !!!Dog
        // </Box>
    )
}

export default VoxelAme
`

voxel-model-loader.js
`
import { forwardRef } from "react";
import { Box, Spinner } from "@chakra-ui/react";

export const AmeSpinner = () => (
    <Spinner
        size='xl'
        position='absolute'
        left='50%'
        top='50%'
        ml='calc(0px - var(--spinner-size) / 2)'
        mt='calc(0px - var(--spinner-size))'
    />
)

export const AmeContainer = forwardRef(({children}, ref) => (
    <Box
        ref={ref}
        className="voxel-ame"
        m="auto"
        mt={['-20px', '-60px', '-120px']}
        mb={['-40px', '-140px', '-200px']}
        w={[280, 480, 640]}
        h={[280, 480, 640]}
        position="relative"
    >
        {children}
    </Box>
))

const Loader = () => {
    return (
      <AmeContainer>
        <AmeSpinner />
      </AmeContainer>
    )
  }
  
  export default Loader
`

and main.js
`
import Head from 'next/head';
import Navbar from '../navbar'
import { Box, Container } from '@chakra-ui/react';
import VoxelAme from '../voxel-ame';
import dynamic from 'next/dynamic'
import VoxelAmeLoader from '../voxel-ame-loader'

const LazyVoxelAme = dynamic(() => import('../voxel-ame'), {
    ssr: false,
    loading: () => <VoxelAmeLoader />
})

const Main = ({ children, router }) => {
    return (
        <Box as="main" pb={8}>
            <Head>
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <title>Tin Tran - Homepage</title>
            </Head>

            <Navbar path={router.asPath} />

            <Container maxW="container.md" pt={14}>
                {/* <NoSsr>
                    <VoxelAme />
                </NoSsr> */}
                {/* <VoxelAme /> */}
                {/* <LazyVoxelAme /> */}
                {children}
            </Container>
        </Box>
    )
}

export default Main;
`

**Comment by craftzdog** [comment]
You should use React 16

**Comment by capedcrusader743** [comment]
> You should use React 16

Thank you so much for the help. Can't believe the man replied to me.
