### ISSUE TITLE
Page not run on mobile safari

### ISSUE THREAD

**Issue by baontq23** [craftzdog/craftzdog-homepage#50]
Device: iPhone XS
Version: iOS 13.7
Browser: Safari
Is there any solution to make it run on older ios versions?
![image](https://user-images.githubusercontent.com/65148766/185609457-458a25ce-4e8d-4ca7-b6f5-fb3de2d7865b.png)

**Comment by craftzdog** [comment]
can't reproduce it and I don't provide user support
