### ISSUE TITLE
extendTheme color for Link component not working

### ISSUE THREAD

**Issue by thomas-gosnet** [craftzdog/craftzdog-homepage#59]
Hi @craftzdog, hope you're doing well, I really enjoy you're content!
While I'm watching you're video, I've notice that the baseStyle for the Link component you're defined in theme.js doesn't work, I can't figure out why.

https://github.com/craftzdog/craftzdog-homepage/blob/7107c5ade0a8a8c8cd9d13294af151f36e85aadf/lib/theme.js#L26-L30

**Comment by craftzdog** [comment]
it works for me

**Comment by thomas-gosnet** [comment]
My mistake I did not notice that you override color property in
https://github.com/craftzdog/craftzdog-homepage/blob/33d7883f8da3de09f5c5cee8eb9a8c7fa3ba5fb0/components/navbar.js#L26-L37
