### ISSUE TITLE
help me

### ISSUE THREAD

**Issue by dzakyabdurhmn** [craftzdog/craftzdog-homepage#68]
clone craftzdog account then change the .glb file without changing the threejs code at all, when I run dev it works but when I run start threejs it doesn't render

https://github.com/dzakyabdurhmn/itskinaa

**Comment by dzakyabdurhmn** [comment]
I want to ask how to build this application and its 3D model

**Comment by craftzdog** [comment]
CORS

**Comment by RuslanFom** [comment]
> clone craftzdog account then change the .glb file without changing the threejs code at all, when I run dev it works but when I run start threejs it doesn't render
> 
> https://github.com/dzakyabdurhmn/itskinaa

Hello. Did you resolved this? I wanna try for practice too, and this 3D doesnt render:(
