### ISSUE TITLE
transparency

### ISSUE THREAD

**Issue by alexguja** [craftzdog/craftzdog-homepage#8]
Hi Takuya,

Really nice work on the homepage website! 

I'm not sure if this is intentional, but I've noticed a small issue with the navbar transparency.
It sometimes causes a text collision with the page content that makes the text unreadable.

You can check it out below.

<img width="1054" alt="screenshot" src="https://user-images.githubusercontent.com/60717961/141100316-dddf4fd5-99f6-4f05-beae-ad724d8c4d2c.png">

**Comment by craftzdog** [comment]
Browser? OS?

**Comment by alexguja** [comment]
I'm using macOS Monteray and Firefox.
I checked it on Safari and it looks awesome there 👍🏻.

**Comment by craftzdog** [comment]
Unfortunately, Firefox doesn't support `backdrop-filter`: https://developer.mozilla.org/en-US/docs/Web/CSS/backdrop-filter

Thanks for the report anyway!
