### ISSUE TITLE
Prettier invalid option

### ISSUE THREAD

**Issue by fariasmateuss** [craftzdog/craftzdog-homepage#9]
Prettier invalid option [here](https://github.com/craftzdog/craftzdog-homepage/blob/05d71e48ad6d03673e7ce0a83f022e6596f09f8a/package.json?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L9)
Did you mean `--write`?

**Comment by craftzdog** [comment]
ah right, but I don't use it

**Comment by fariasmateuss** [comment]
I'll fix this one in a PR, okay?

**Comment by craftzdog** [comment]
yep, please
